version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:10.4-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

  web:
    image: web
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "127.0.0.1:8000:80"

  app:
    image: app
    build: .
    env_file: .env
    environment:
      DB_HOST: db
      APP_HOST: 0.0.0.0
